#!/bin/bash

start(){
    echo "Start firewall"
    /sbin/depmod -a
    /sbin/modprobe ip_tables
    /sbin/modprobe ip_conntrack
    /sbin/modprobe iptable_filter
    /sbin/modprobe iptable_mangle
    /sbin/modprobe iptable_nat
    /sbin/modprobe ipt_LOG
    /sbin/modprobe ipt_limit
    /sbin/modprobe ipt_state
    echo "1" > /proc/sys/net/ipv4/ip_forward

    iptables -t nat -A POSTROUTING -s 172.16.55.86 -o eth0 -j SNAT --to 172.16.55.90
    iptables -t nat -A POSTROUTING -s 172.16.55.98 -o eth0 -j SNAT --to 172.16.55.90
    iptables -t nat -A POSTROUTING -s 172.16.55.131 -o eth0 -j SNAT --to 172.16.55.90
    iptables -t nat -A POSTROUTING -s 172.16.55.132 -o eth0 -j SNAT --to 172.16.55.90
    iptables -t nat -A POSTROUTING -s 172.16.55.134 -o eth0 -j SNAT --to 172.16.55.90
    iptables -t nat -A POSTROUTING -s 172.16.55.135 -o eth0 -j SNAT --to 172.16.55.90
}
stop(){
    echo "Stop firewall"
    echo "0" > /proc/sys/net/ipv4/ip_forward
    iptables -P INPUT ACCEPT
    iptables -P FORWARD ACCEPT
    iptables -P OUTPUT ACCEPT
    iptables -t nat -P PREROUTING ACCEPT
    iptables -t nat -P POSTROUTING ACCEPT
    iptables -t nat -P OUTPUT ACCEPT
    iptables -t mangle -P PREROUTING ACCEPT
    iptables -t mangle -P OUTPUT ACCEPT
    iptables -F
    iptables -t nat -F
    iptables -t mangle -F
    iptables -X
    iptables -t nat -X
    iptables -t mangle -X
}
status(){
    clear
    echo "-------------------------------------------------------------------"
    iptables -L
    echo "-------------------------------------------------------------------"
    iptables -t nat -L POSTROUTING
    echo "-------------------------------------------------------------------"
    iptables -t nat -L PREROUTING
}
case "$1" in
start)
        start
;;
stop)
        stop
;;
status)
        status
;;
restart)
        stop
        start
;;
*)
        echo "$0 [start|stop|restart|status]"
;;
esac
